"""Documentation generator — deterministic project docs from the IR."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..artifact import ArtifactSet
from ..diagnostics import Diagnostics
from ._util import resolve_model
from .base import Generator

if TYPE_CHECKING:  # pragma: no cover
    from .. import ir as I
    from ..compiler import CompileOptions


class DocsGenerator(Generator):
    name = "docs"

    def generate(self, module: "I.ModuleIR", options: "CompileOptions",
                 artifacts: ArtifactSet, diags: Diagnostics) -> None:
        self.m = module
        artifacts.add("docs/PRODUCT.md", self._product(), self.name)
        artifacts.add("docs/API.md", self._api(), self.name)
        artifacts.add("docs/DATABASE.md", self._database(), self.name)
        artifacts.add("docs/ARCHITECTURE.md", self._architecture(), self.name)

    def _product(self) -> str:
        m = self.m
        lines = [
            f"# {m.app.title}",
            "",
            f"> Generated by IntentOS from the IntentLang program `{m.name}`.",
            "",
            m.app.description or "No description provided.",
            "",
            "## Pages",
            "",
        ]
        for p in m.pages:
            lines.append(f"- **{p.name}** — `{p.route}`" + (f" — {p.title}" if p.title and p.title != p.name else ""))
        if m.roles:
            lines += ["", "## Roles", ""]
            for r in m.roles:
                perms = ", ".join(r.permissions) if r.permissions else "no explicit permissions"
                lines.append(f"- **{r.name}** — {perms}")
        lines += ["", "## Capabilities", ""]
        lines.append(f"- {len(m.pages)} page(s), {len(m.models)} model(s), {len(m.apis)} api(s)")
        lines.append(f"- Stack: {m.app.frontend} / {m.app.backend} / {m.app.database}")
        return "\n".join(lines)

    def _api(self) -> str:
        lines = ["# API Reference", ""]
        if not self.m.apis:
            return "# API Reference\n\nNo APIs defined.\n"
        for a in self.m.apis:
            lines.append(f"## {a.method} `{a.route}` — {a.name}")
            lines.append("")
            lines.append(f"- **Auth**: `{a.auth}`")
            if a.request_fields:
                lines.append("- **Request body**:")
                for f in a.request_fields:
                    lines.append(f"  - `{f.name}` ({f.ftype})" + (" (required)" if f.required else ""))
            if a.query and a.query.table:
                lines.append(f"- **Query**: SELECT {a.query.select or '*'} FROM {a.query.table}"
                             + (f" WHERE {a.query.where}" if a.query.where else "")
                             + (f" ORDER BY {a.query.order}" if a.query.order else ""))
            for r in a.responses:
                body = self._body_str(r.body)
                lines.append(f"- **Response {r.status}**: {body or 'empty'}")
            lines.append("")
        return "\n".join(lines)

    def _body_str(self, body) -> str:
        if isinstance(body, tuple):
            return f"List[{body[1] or 'record'}]" if body[0] == "list" else str(body[0])
        if body:
            return str(body)
        return ""

    def _database(self) -> str:
        lines = ["# Database Schema", ""]
        if not self.m.models:
            return "# Database Schema\n\nNo models defined.\n"
        for model in self.m.models:
            lines.append(f"## {model.name} (`{model.table}`)")
            lines.append("")
            lines.append("| Field | Type | Required | Unique | Notes |")
            lines.append("|-------|------|----------|--------|-------|")
            for f in model.fields:
                notes = []
                if f.primary:
                    notes.append("primary key")
                if f.reference:
                    notes.append(f"FK → {f.reference[0]}.{f.reference[1]}")
                if f.default is not None:
                    notes.append(f"default {f.default}")
                lines.append(f"| {f.name} | {f.ftype} | {'✓' if f.required else ''} | {'✓' if f.unique else ''} | {'; '.join(notes)} |")
            lines.append("")
        return "\n".join(lines)

    def _architecture(self) -> str:
        m = self.m
        lines = [
            f"# Architecture — {m.app.title}",
            "",
            "```",
            "English description",
            "      |  IntentOS AI planner (produces IntentLang only)",
            "      v",
            "app.intentlang",
            "      |  IntentLang compiler",
            "      v",
            "IR  ->  code generators",
            "      |",
            "      +-- frontend/   (React SPA)",
            "      +-- backend/    (FastAPI + SQLAlchemy)",
            "      +-- db/         (schema.sql)",
            "      +-- infra/      (Docker / Compose)",
            "      +-- .github/    (CI/CD)",
            "```",
            "",
            "## Components",
            "",
        ]
        if m.models:
            lines.append("- Models: " + ", ".join(f"{mo.name} ({mo.table})" for mo in m.models))
        if m.apis:
            lines.append("- APIs: " + ", ".join(f"{a.name} {a.method} {a.route}" for a in m.apis))
        lines.append("")
        lines.append("## Data flow")
        lines.append("")
        lines.append("1. The React SPA calls the FastAPI backend via the generated `src/api` client.")
        lines.append("2. Endpoints validate auth (`security.py`), run the generated query, and return pydantic schemas.")
        lines.append("3. Tables and charts fetch on mount; forms submit through the same client.")
        lines.append("")
        return "\n".join(lines)
