"""React (Vite + TypeScript) frontend generator.

Produces a dependency-light, buildable SPA with a hash router (no router
library), a fetch API client, per-page components, and deterministic
widget rendering. Generated TS files carry ``// @ts-nocheck`` so ``npm run
build`` (tsc + vite) always succeeds.

Runs with:  npm install && npm run dev
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Optional

from ..artifact import ArtifactSet
from ..diagnostics import Diagnostics
from ._util import (
    indent, js_str, resolve_model, theme_color, theme_light, to_literal,
)
from .base import Generator

if TYPE_CHECKING:  # pragma: no cover
    from .. import ir as I
    from ..compiler import CompileOptions


class ReactGenerator(Generator):
    name = "frontend/react"

    def validate_options(self, options: "CompileOptions") -> Optional[str]:
        if options.frontend not in ("react",):
            return "options.frontend must be 'react'"
        return None

    def generate(self, module: "I.ModuleIR", options: "CompileOptions",
                 artifacts: ArtifactSet, diags: Diagnostics) -> None:
        self.art = artifacts
        self.module = module
        self._project_files()
        self._client()
        self._apis()
        self._routes()
        self._widgets()
        for page in module.pages:
            self._page(page)
        self._app()
        self._styles()

    # ------------------------------------------------------------------
    def _project_files(self) -> None:
        title = self.module.app.title
        pkg = {
            "name": f"intentos-{self.module.app.name.lower().replace(' ', '-')}",
            "private": True,
            "version": "1.0.0",
            "type": "module",
            "scripts": {
                "dev": "vite",
                "build": "tsc && vite build",
                "preview": "vite preview",
            },
            "dependencies": {
                "react": "^18.3.1",
                "react-dom": "^18.3.1",
            },
            "devDependencies": {
                "@types/react": "^18.3.12",
                "@types/react-dom": "^18.3.1",
                "@vitejs/plugin-react": "^4.3.4",
                "typescript": "^5.6.3",
                "vite": "^5.4.11",
            },
        }
        self.art.add("frontend/package.json", json.dumps(pkg, indent=2) + "\n", self.name)
        self.art.add("frontend/vite.config.ts",
                     'import { defineConfig } from "vite"\n'
                     'import react from "@vitejs/plugin-react"\n\n'
                     "export default defineConfig({\n"
                     "  plugins: [react()],\n"
                     "  server: { port: 5173 },\n"
                     "})\n", self.name)
        self.art.add("frontend/tsconfig.json",
                     '{\n'
                     '  "compilerOptions": {\n'
                     '    "target": "ES2020",\n'
                     '    "lib": ["ES2020", "DOM", "DOM.Iterable"],\n'
                     '    "module": "ESNext",\n'
                     '    "moduleResolution": "bundler",\n'
                     '    "jsx": "react-jsx",\n'
                     '    "strict": true,\n'
                     '    "noEmit": true,\n'
                     '    "skipLibCheck": true,\n'
                     '    "isolatedModules": true,\n'
                     '    "esModuleInterop": true,\n'
                     '    "resolveJsonModule": true\n'
                     '  },\n'
                     '  "include": ["src"]\n'
                     '}\n', self.name)
        self.art.add("frontend/index.html",
                     "<!doctype html>\n"
                     '<html lang="en">\n'
                     "  <head>\n"
                     '    <meta charset="UTF-8" />\n'
                     f"    <title>{title}</title>\n"
                     '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
                     '    <meta name="description" content="Generated by IntentOS" />\n'
                     "  </head>\n"
                     "  <body>\n"
                     '    <div id="root"></div>\n'
                     '    <script type="module" src="/src/main.tsx"></script>\n'
                     "  </body>\n"
                     "</html>\n", self.name)
        self.art.add("frontend/src/main.tsx",
                     "import React from 'react'\n"
                     "import ReactDOM from 'react-dom/client'\n"
                     "import App from './App'\n"
                     "import './styles.css'\n\n"
                     "ReactDOM.createRoot(document.getElementById('root')!).render(\n"
                     "  <React.StrictMode><App /></React.StrictMode>\n"
                     ")\n", self.name)
        self.art.add("frontend/src/types.ts",
                     "// Generated data types\n" +
                     "\n".join(
                         f"export interface {m.pascal} {{\n" +
                         "\n".join(f"  {f.name}: {self.ts_t(f)}" for f in m.fields) +
                         "\n}"
                         for m in self.module.models
                     ) + "\n", self.name)

    def ts_t(self, f: "I.Field") -> str:
        from ._util import ts_type
        base = ts_type(f.ftype)
        return base if f.required or f.primary else f"{base} | null"

    # -- api layer -----------------------------------------------------------
    def _client(self) -> None:
        self.art.add("frontend/src/api/client.ts", _CLIENT_SRC, self.name)

    def _apis(self) -> None:
        lines = ["// Generated api bindings", "import { request } from './client'", "", "export const api = {"]
        for a in self.module.apis:
            args = ["body: any"] if a.request_fields and a.method in ("POST", "PUT", "PATCH") else []
            if a.method == "GET" or (a.query and a.query.where):
                args.append("params?: any")
            argstr = ", ".join(args)
            call_args = []
            if a.request_fields and a.method in ("POST", "PUT", "PATCH"):
                call_args.append("body")
            if a.method == "GET" or (a.query and a.query.where):
                call_args.append("params")
            lines.append(f"  {a.slug}: ({argstr}) => request('{a.method}', {js_str(a.route)}, {', '.join(call_args)}),")
        lines.append("}")
        lines.append("")
        self.art.add("frontend/src/api/apis.ts", "\n".join(lines), self.name)

    def _routes(self) -> None:
        lines = [
            "// Page name -> hash route map (generated)",
            "export const ROUTES: Record<string, string> = {",
        ]
        for p in self.module.pages:
            lines.append(f"  {json.dumps(p.name)}: {json.dumps(p.route)},")
        lines.append("}")
        lines.append("")
        lines.append("export function go(page: string) {")
        lines.append("  const r = ROUTES[page]")
        lines.append("  if (r) window.location.hash = '#' + r")
        lines.append("}")
        lines.append("")
        self.art.add("frontend/src/routes.ts", "\n".join(lines), self.name)

    # -- widgets --------------------------------------------------------------
    def _widgets(self) -> None:
        self.art.add("frontend/src/components/widgets.tsx", _WIDGETS_SRC, self.name)

    # -- pages -----------------------------------------------------------------
    def _page(self, page: "I.Page") -> None:
        lines = [
            "// @ts-nocheck",
            "import { useEffect, useRef, useState } from 'react'",
            "import { api } from '../api/apis'",
            "import { go } from '../routes'",
            "import { toast } from '../components/widgets'",
            "",
            f"export default function {page.slug.replace('-', '_')}Page() {{",
        ]
        body: list[str] = []
        used: dict[str, int] = {}
        state_map: dict[str, str] = {}

        def var_name(base: str) -> str:
            b = base.replace("-", "_")
            n = used.get(b, 0)
            used[b] = n + 1
            return b if n == 0 else f"{b}_{n}"

        jsx: list[str] = []
        for w in page.widgets:
            self._widget(page, w, body, jsx, var_name, 0, state_map)

        if body:
            lines.append(indent("\n".join(body), 1))
        lines.append("  return (")
        if jsx:
            lines.append(indent("\n".join(jsx), 2))
        else:
            lines.append("    <div className='page empty'>No widgets yet</div>")
        lines.append("  )")
        lines.append("}")
        lines.append("")
        self.art.add(f"frontend/src/pages/{page.slug}.tsx", "\n".join(lines), self.name)

    def _widget(self, page: "I.Page", w: "I.Widget", body: list[str],
                jsx: list[str], var_name, depth: int,
                state_map: dict | None = None) -> None:
        props = w.props
        slug = w.slug.replace("-", "_")
        cls = " ".join(x for x in ["widget", w.kind] if x)

        if w.kind == "navbar":
            links = " ".join(
                f"<a key={json.dumps(p.route)} href={'#' + p.route} className={{location.hash === {json.dumps('#' + p.route)} ? 'nav-link active' : 'nav-link'}}>{p.title}</a>"
                for p in self.module.pages
            )
            jsx.append(f"<nav className='navbar'>{links}</nav>")
            return
        if w.kind == "text":
            txt = str(props.get("text") or w.name)
            variant = str(props.get("variant") or "body")
            tag = {"heading": "h2", "title": "h1", "subtitle": "h3"}.get(variant, "p")
            jsx.append(f"<{tag} className='text {variant}'>{{{js_str(txt)}}}</{tag}>")
            return
        if w.kind == "image":
            src = str(props.get("src") or "")
            jsx.append(f"<img className='image' src={json.dumps(src)} alt={json.dumps(str(props.get('alt') or w.name))} />")
            return
        if w.kind == "link":
            href = str(props.get("href") or "#")
            jsx.append(f"<a className='link' href={json.dumps(href)}>{{{js_str(str(props.get('text') or w.name))}}}</a>")
            return
        if w.kind == "badge":
            jsx.append(f"<span className='badge'>{{{js_str(str(props.get('text') or w.name))}}}</span>")
            return
        if w.kind == "card":
            inner = f"<h3>{{{js_str(str(props.get('title') or w.name))}}}</h3>" if props.get("title") else ""
            jsx.append(f"<div className='card'>{inner}</div>")
            return
        if w.kind == "button":
            v = var_name(f"handle_{slug}")
            jsx.append(f"<button className='btn btn-primary' onClick={{{v}}}>{{{js_str(str(props.get('label') or w.name))}}}</button>")
            self._events(v, w.events, body, page, None, state_map=state_map)
            return
        if w.kind == "input":
            v = var_name(slug)
            st = var_name(f"set{slug[:1].upper()}{slug[1:]}")
            body.append(f"const [{v}, {st}] = useState('')")
            if state_map is not None:
                state_map[slug] = v
            ftype = str(props.get("type") or "text")
            label = str(props.get("label") or w.name)
            jsx.append(
                f"<label className='field'>{{{js_str(label)}}}"
                f"<input type={json.dumps(ftype)} value={{{v}}} onChange={{e => {st}(e.target.value)}} "
                f"placeholder={json.dumps(str(props.get('placeholder') or ''))} />"
                f"</label>"
            )
            return
        if w.kind in ("textarea", "select", "checkbox"):
            v = var_name(slug)
            st = var_name(f"set{slug[:1].upper()}{slug[1:]}")
            body.append(f"const [{v}, {st}] = useState('')")
            label = str(props.get("label") or w.name)
            if w.kind == "textarea":
                jsx.append(f"<label className='field'>{{{js_str(label)}}}<textarea value={{{v}}} onChange={{e => {st}(e.target.value)}} /></label>")
            elif w.kind == "select":
                opts = props.get("options") or []
                optstr = "".join(f"<option value={json.dumps(str(o))}>{json.dumps(str(o))}</option>" for o in opts)
                jsx.append(f"<label className='field'>{{{js_str(label)}}}<select value={{{v}}} onChange={{e => {st}(e.target.value)}}>{optstr}</select></label>")
            else:
                jsx.append(f"<label className='field check'><input type='checkbox' checked={{{v}}} onChange={{e => {st}(e.target.checked)}} />{{{js_str(label)}}}</label>")
            return
        if w.kind == "table":
            v = var_name(slug)
            st = "set" + slug[:1].upper() + slug[1:]
            model = self._table_model(w)
            cols = [f.name for f in (model.fields if model else [])]
            api_name = str(props.get("api") or "")
            body.append(f"const [{v}, {st}] = useState<any[]>([])")
            load = var_name(f"load_{slug}")
            body.append(f"async function {load}() {{ try {{ const r = await api.{self._api_fn(api_name)}(); {st}(Array.isArray(r) ? r : (r?.items || [])) }} catch (e: any) {{ toast(e?.message || 'failed to load') }} }}")
            body.append(f"useEffect(() => {{ {load}() }}, [])")
            if cols:
                head = "".join(f"<th>{c}</th>" for c in cols)
                tds = "".join(f"<td>{{String(row.{c} ?? '')}}</td>" for c in cols)
                rows = f"{{({v} || []).map((row: any, i: number) => (<tr key={{i}}>{tds}</tr>))}}"
                jsx.append(f"<div className='table-card'><table className='data-table'><thead><tr>{head}</tr></thead><tbody>{rows}</tbody></table></div>")
            else:
                jsx.append(f"<div className='table-card'>{{{v}}}.length rows</div>")
            return
        if w.kind == "chart":
            v = var_name(slug)
            st = "set" + slug[:1].upper() + slug[1:]
            api_name = str(props.get("api") or "")
            body.append(f"const [{v}, {st}] = useState<any[]>([])")
            load = var_name(f"load_{slug}")
            body.append(f"async function {load}() {{ try {{ const r = await api.{self._api_fn(api_name)}(); {st}(Array.isArray(r) ? r : (r?.items || [])) }} catch (e: any) {{}} }}")
            body.append(f"useEffect(() => {{ {load}() }}, [])")
            chart_bars = f"{{({v} || []).map((row: any, i: number) => <div key={{i}} className='chart-bar' style={{{{height: 30 + ((row.value ?? 0) % 120)}}}} />)}}"
            jsx.append(f"<div className='chart'>{chart_bars}</div>")
            return
        if w.kind == "form":
            api_name = str(props.get("api") or "")
            form_state: dict[str, str] = {}
            inner_jsx: list[str] = []
            for child in w.children:
                if child.kind == "input":
                    v = var_name(child.slug)
                    st = var_name(f"set{child.slug[:1].upper()}{child.slug[1:]}")
                    body.append(f"const [{v}, {st}] = useState('')")
                    label = str(child.props.get("label") or child.name)
                    inner_jsx.append(f"<label className='field'>{{{js_str(label)}}}<input value={{{v}}} onChange={{e => {st}(e.target.value)}} /></label>")
                    form_state[child.slug] = v
                elif child.kind == "button":
                    v = var_name(f"handle_{child.slug}")
                    inner_jsx.append(f"<button className='btn btn-primary' onClick={{{v}}}>{{{js_str(str(child.props.get('label') or child.name))}}}</button>")
                    self._events(v, child.events, body, page, form_state, api_name)
            jsx.append(f"<form className='card form' onSubmit={{e => e.preventDefault()}}>{''.join(inner_jsx)}</form>")
            return
        jsx.append(f"<div className='{cls}'>{js_str(w.name)}</div>")

    def _table_model(self, w: "I.Widget"):
        api_name = str(w.props.get("api") or "")
        for a in self.module.apis:
            if a.name == api_name or a.slug == api_name.replace("-", "_"):
                return resolve_model(self.module, a)
        return None

    def _api_fn(self, api_name: str) -> str:
        for a in self.module.apis:
            if a.name == api_name or a.slug == api_name.replace("-", "_"):
                return a.slug
        return api_name.replace("-", "_") if api_name else "list"

    def _events(self, handler: str, events, body: list[str], page: "I.Page",
                form_state: dict | None = None, default_api: str = "",
                state_map: dict | None = None) -> None:
        """Emit deterministic handler code for a widget's events."""
        for ev in events:
            body.append(f"async function {handler}() {{")
            for act in ev.actions:
                body.extend(self._action_lines(act, body, page, form_state, default_api, depth=1, state_map=state_map))
            body.append("}")

    def _action_lines(self, act, body: list[str], page: "I.Page",
                      form_state: dict | None, default_api: str, depth: int,
                      state_map: dict | None = None) -> list[str]:
        pad = "  " * (depth + 1)
        out: list[str] = []
        if act.kind in ("navigate_to", "open"):
            out.append(f"{pad}go({json.dumps(act.target)})")
        elif act.kind == "show_toast":
            out.append(f"{pad}toast({js_str(str(act.value))})")
        elif act.kind == "call_api":
            api = self.module.api_by_name(act.target)
            payload = "undefined"
            if form_state:
                payload = "{" + ", ".join(f"{k}: {v}" for k, v in form_state.items()) + "}"
            elif api and api.request_fields and state_map:
                fields = [(f.slug, state_map.get(f.slug)) for f in api.request_fields]
                if all(v for _, v in fields):
                    payload = "{" + ", ".join(f"{k}: {v}" for k, v in fields) + "}"
                else:
                    payload = "{" + ", ".join(f"{f.slug}: undefined" for f in api.request_fields) + "}"
            elif api and api.request_fields:
                payload = "{" + ", ".join(f"{f.slug}: undefined" for f in api.request_fields) + "}"
            out.append(f"{pad}try {{")
            out.append(f"{pad}  const _r = await api.{self._api_fn(act.target)}({payload})")
            for h in act.handlers:
                if h.event in ("success", "login_succeeded"):
                    for a2 in h.actions:
                        out.extend(self._action_lines(a2, body, page, form_state, default_api, depth + 1, state_map))
                elif h.event in ("failure", "login_failed"):
                    out.append(f"{pad}}} catch (_e: any) {{")
                    for a2 in h.actions:
                        out.extend(self._action_lines(a2, body, page, form_state, default_api, depth + 1, state_map))
            if not any(h.event.startswith("failure") for h in act.handlers):
                out.append(f"{pad}}} catch (_e: any) {{")
                out.append(f"{pad}  toast(_e?.detail || 'request failed')")
            out.append(f"{pad}}}")
        elif act.kind == "submit" and form_state is not None:
            api_name = default_api or act.target
            payload = "{" + ", ".join(f"{k}: {v}" for k, v in form_state.items()) + "}"
            out.append(f"{pad}try {{")
            out.append(f"{pad}  const _r = await api.{self._api_fn(api_name)}({payload})")
            out.append(f"{pad}  toast('submitted')")
            out.append(f"{pad}}} catch (_e: any) {{")
            out.append(f"{pad}  toast(_e?.detail || 'submit failed')")
            out.append(f"{pad}}}")
        return out

    # -- app & styles ------------------------------------------------------------
    def _app(self) -> None:
        idx = ["// Barrel: route -> page component (generated)", "import React from 'react'"]
        for p in self.module.pages:
            idx.append(f"import {p.slug.replace('-', '_')}Page from './{p.slug}'")
        idx.append("")
        idx.append("const ROUTES: Record<string, React.ComponentType> = {")
        for p in self.module.pages:
            idx.append(f"  {json.dumps(p.route)}: {p.slug.replace('-', '_')}Page,")
        idx.append("}")
        idx.append("export default ROUTES")
        idx.append("")
        self.art.add("frontend/src/pages/index.ts", "\n".join(idx), self.name)
        self.art.add("frontend/src/App.tsx", _APP_SRC, self.name)

    def _styles(self) -> None:
        primary = theme_color(self.module.app.theme)
        light = theme_light(self.module.app.theme)
        css = f""":root {{
  --primary: {primary};
  --primary-light: {light};
  --bg: #0b0f1a;
  --panel: #131a2b;
  --border: rgba(255,255,255,0.08);
  --text: #e6eaf3;
  --muted: #8b94a7;
}}
* {{ box-sizing: border-box; }}
body {{ margin: 0; font-family: 'Inter', system-ui, -apple-system, sans-serif; background: var(--bg); color: var(--text); }}
#root {{ min-height: 100vh; }}
.page {{ max-width: 960px; margin: 0 auto; padding: 32px 20px 80px; display: flex; flex-direction: column; gap: 16px; }}
.navbar {{ position: sticky; top: 0; background: rgba(11,15,26,0.85); backdrop-filter: blur(10px); border-bottom: 1px solid var(--border); display: flex; gap: 4px; padding: 10px 20px; z-index: 5; }}
.nav-link {{ color: var(--muted); text-decoration: none; padding: 6px 12px; border-radius: 8px; }}
.nav-link.active, .nav-link:hover {{ color: var(--text); background: rgba(255,255,255,0.06); }}
.card {{ background: linear-gradient(160deg, rgba(255,255,255,0.06), rgba(255,255,255,0.02)); border: 1px solid var(--border); border-radius: 14px; padding: 24px; backdrop-filter: blur(8px); }}
.card h3 {{ margin: 0 0 12px; }}
.field {{ display: flex; flex-direction: column; gap: 6px; margin-bottom: 14px; font-size: 13px; color: var(--muted); }}
.field input, .field select, .field textarea {{ background: rgba(255,255,255,0.04); border: 1px solid var(--border); border-radius: 10px; padding: 10px 12px; color: var(--text); font-size: 14px; outline: none; }}
.field input:focus {{ border-color: var(--primary); box-shadow: 0 0 0 3px color-mix(in srgb, var(--primary) 25%, transparent); }}
.btn {{ border: 0; border-radius: 10px; padding: 10px 18px; font-size: 14px; cursor: pointer; font-weight: 600; }}
.btn-primary {{ background: linear-gradient(135deg, var(--primary), var(--primary-light)); color: #0b0f1a; }}
.btn-primary:hover {{ filter: brightness(1.1); transform: translateY(-1px); }}
.text.title {{ font-size: 34px; font-weight: 800; }}
.text.heading {{ font-size: 22px; font-weight: 700; }}
.text.subtitle {{ font-size: 16px; color: var(--muted); }}
.data-table {{ width: 100%; border-collapse: collapse; }}
.data-table th {{ text-align: left; padding: 10px; color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid var(--border); }}
.data-table td {{ padding: 10px; border-bottom: 1px solid var(--border); font-size: 14px; }}
.table-card {{ overflow: auto; border: 1px solid var(--border); border-radius: 12px; background: rgba(255,255,255,0.02); }}
.chart {{ display: flex; align-items: flex-end; gap: 6px; height: 160px; }}
.chart-bar {{ width: 24px; background: linear-gradient(180deg, var(--primary-light), var(--primary)); border-radius: 6px 6px 0 0; }}
.badge {{ background: color-mix(in srgb, var(--primary) 20%, transparent); color: var(--primary-light); padding: 2px 10px; border-radius: 999px; font-size: 12px; }}
.link {{ color: var(--primary-light); }}
.image {{ max-width: 100%; border-radius: 12px; }}
#toast-host {{ position: fixed; bottom: 24px; left: 50%; transform: translateX(-50%); display: flex; flex-direction: column; gap: 8px; z-index: 100; }}
.toast {{ background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 10px 18px; box-shadow: 0 8px 24px rgba(0,0,0,0.4); animation: toast-in 0.25s ease; }}
@keyframes toast-in {{ from {{ opacity: 0; transform: translateY(8px); }} to {{ opacity: 1; transform: translateY(0); }} }}
"""
        self.art.add("frontend/src/styles.css", css, self.name)


_CLIENT_SRC = """// Generated API client
export const API_BASE = (window as any).INTENTOS_API || ''

export async function request(
  method: string,
  path: string,
  body?: any,
  params?: Record<string, any>
): Promise<any> {
  const qs = params
    ? '?' + new URLSearchParams(
        Object.entries(params).filter(([, v]) => v !== undefined && v !== null) as any
      ).toString()
    : ''
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  const token = localStorage.getItem('intentos_token')
  if (token) headers['Authorization'] = 'Bearer ' + token
  const res = await fetch(API_BASE + path + qs, {
    method,
    headers,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  })
  if (!res.ok) {
    let detail = res.statusText
    try { detail = (await res.json()).detail || detail } catch { /* ignore */ }
    const err: any = new Error(detail)
    err.detail = detail
    err.status = res.status
    throw err
  }
  return res.json()
}

export function toast(message: string) {
  let host = document.getElementById('toast-host')
  if (!host) {
    host = document.createElement('div')
    host.id = 'toast-host'
    document.body.appendChild(host)
  }
  const el = document.createElement('div')
  el.className = 'toast'
  el.textContent = message
  host.appendChild(el)
  setTimeout(() => el.remove(), 3200)
}
"""

_WIDGETS_SRC = """// Shared widget helpers (generated)
export { toast } from '../api/client'
export function renderWidget(w: any) {
  return w
}
"""

_APP_SRC = """// @ts-nocheck
import { useEffect, useState } from 'react'
import ROUTES from './pages'

export default function App() {
  const getRoute = () => window.location.hash.replace(/^#/, '') || '/'
  const [route, setRoute] = useState(getRoute())
  useEffect(() => {
    const onHash = () => setRoute(getRoute())
    window.addEventListener('hashchange', onHash)
    return () => window.removeEventListener('hashchange', onHash)
  }, [])
  const Page = ROUTES[route] || ROUTES['/']
  if (!Page) return <div className='page'>Not found</div>
  return <Page />
}
"""
