"""Flutter (Dart) frontend generator."""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Optional

from ..artifact import ArtifactSet
from ..diagnostics import Diagnostics
from ._util import dart_str, dart_type, theme_color, theme_light
from .base import Generator

if TYPE_CHECKING:  # pragma: no cover
    from .. import ir as I
    from ..compiler import CompileOptions


class FlutterGenerator(Generator):
    name = "frontend/flutter"

    def validate_options(self, options: "CompileOptions") -> Optional[str]:
        if options.frontend not in ("flutter", "dart"):
            return "options.frontend must be 'flutter'"
        return None

    def generate(self, module: "I.ModuleIR", options: "CompileOptions",
                 artifacts: ArtifactSet, diags: Diagnostics) -> None:
        self.art = artifacts
        self.module = module
        self._pubspec()
        self._main()
        self._theme()
        self._api()
        for model in module.models:
            self._model(model)
        for page in module.pages:
            self._page(page)

    def _pubspec(self) -> None:
        name = "intentos_" + module_name(self.module.app.name)
        self.art.add(
            "frontend/pubspec.yaml",
            f"name: {name}\n"
            "description: Generated by IntentOS\n"
            "publish_to: 'none'\n"
            "version: 1.0.0+1\n\n"
            "environment:\n"
            "  sdk: '>=3.3.0 <4.0.0'\n\n"
            "dependencies:\n"
            "  flutter:\n"
            "    sdk: flutter\n"
            "  http: ^1.2.0\n\n"
            "dev_dependencies:\n"
            "  flutter_test:\n"
            "    sdk: flutter\n\n"
            "flutter:\n"
            "  uses-material-design: true\n", self.name,
        )

    def _main(self) -> None:
        routes = ",\n".join(
            f"        {json.dumps(p.route)}: (context) => const {p.slug.replace('-', '_')}Page()"
            for p in self.module.pages
        )
        self.art.add(
            "frontend/lib/main.dart",
            "import 'package:flutter/material.dart';\n"
            "import 'theme.dart';\n"
            "import 'pages/" + self.module.pages[0].slug.replace('-', '_') + ".dart';\n"
            if self.module.pages else
            "import 'package:flutter/material.dart';\n"
            "import 'theme.dart';\n"
            ""
            "\nvoid main() => runApp(const IntentosApp());\n\n"
            "class IntentosApp extends StatelessWidget {\n"
            "  const IntentosApp({super.key});\n\n"
            "  @override\n"
            "  Widget build(BuildContext context) {\n"
            "    return MaterialApp(\n"
            "      title: " + dart_str(self.module.app.title) + ",\n"
            "      theme: buildTheme(),\n"
            "      initialRoute: '/',\n"
            "      routes: {\n" + routes + "\n"
            "      },\n"
            "    );\n"
            "  }\n"
            "}\n", self.name,
        )

    def _theme(self) -> None:
        primary = theme_color(self.module.app.theme)
        self.art.add(
            "frontend/lib/theme.dart",
            "import 'package:flutter/material.dart';\n\n"
            "ThemeData buildTheme() {\n"
            "  return ThemeData(\n"
            "    brightness: Brightness.dark,\n"
            f"    colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xff{primary[1:]})),\n"
            "    scaffoldBackgroundColor: const Color(0xff0b0f1a),\n"
            "  );\n"
            "}\n", self.name,
        )

    def _api(self) -> None:
        lines = [
            "import 'dart:convert';\n",
            "import 'package:http/http.dart' as http;\n",
            "",
            "const String apiBase = String.fromEnvironment('API_BASE', defaultValue: 'http://localhost:8000');\n",
            "",
            "Future<dynamic> request(String method, String path, [Map<String, dynamic>? body]) async {\n",
            "  final uri = Uri.parse('$apiBase$path');\n",
            "  final headers = {'Content-Type': 'application/json'};\n",
            "  final http.Response res;\n",
            "  switch (method) {\n",
            "    case 'GET': res = await http.get(uri, headers: headers); break;\n",
            "    case 'POST': res = await http.post(uri, headers: headers, body: jsonEncode(body ?? {})); break;\n",
            "    case 'PUT': res = await http.put(uri, headers: headers, body: jsonEncode(body ?? {})); break;\n",
            "    case 'DELETE': res = await http.delete(uri, headers: headers); break;\n",
            "    default: throw UnsupportedError(method);\n",
            "  }\n",
            "  if (res.statusCode >= 300) {\n",
            "    throw Exception('${res.statusCode}: request failed');\n",
            "  }\n",
            "  return jsonDecode(utf8.decode(res.bodyBytes));\n",
            "}\n",
            "",
        ]
        for a in self.module.apis:
            args = ["[Map<String, dynamic>? body]"] if a.request_fields and a.method in ("POST", "PUT", "PATCH") else []
            body_arg = "body" if args else ""
            lines.append(f"Future<dynamic> api{a.pascal}({', '.join(args)}) => ")
            lines.append(f"    request('{a.method}', {dart_str(a.route)}, {body_arg});")
        self.art.add("frontend/lib/services/api.dart", "\n".join(lines), self.name)

    def _model(self, model: "I.Model") -> None:
        lines = [
            "class " + model.pascal + " {\n",
        ]
        for f in model.fields:
            lines.append(f"  final {dart_type(f.ftype)} {f.name};")
        lines.append("")
        args = ", ".join(f"this.{f.name}" for f in model.fields)
        lines.append(f"  {model.pascal}({{{args}}});")
        lines.append("")
        lines.append(f"  factory {model.pascal}.fromJson(Map<String, dynamic> json) => {model.pascal}(")
        for f in model.fields:
            cast = ""
            if dart_type(f.ftype) in ("int",):
                cast = " as int"
            elif dart_type(f.ftype) == "double":
                cast = " as num).toDouble()"
            elif dart_type(f.ftype) == "bool":
                cast = " as bool"
            elif dart_type(f.ftype) == "DateTime":
                cast = " != null ? DateTime.parse(json['" + f.name + "'] as String) : null"
            lines.append(f"    {f.name}: json['{f.name}']{cast},")
        lines.append("  );")
        lines.append("}")
        lines.append("")
        self.art.add(f"frontend/lib/models/{model.slug}.dart", "\n".join(lines), self.name)

    def _page(self, page: "I.Page") -> None:
        lines = [
            "import 'package:flutter/material.dart';",
            "import '../services/api.dart';",
            "",
            f"class {page.slug.replace('-', '_')}Page extends StatelessWidget {{",
            f"  const {page.slug.replace('-', '_')}Page({{super.key}});",
            "",
            "  @override",
            "  Widget build(BuildContext context) {",
            "    return Scaffold(",
            f"      appBar: AppBar(title: Text({dart_str(page.title)})),",
            "      body: ListView(padding: const EdgeInsets.all(16), children: const [",
        ]
        for w in page.widgets:
            line = self._widget(w)
            lines.append("        " + line + ",")
        lines.append("      ]),")
        lines.append("    );")
        lines.append("  }")
        lines.append("}")
        lines.append("")
        self.art.add(f"frontend/lib/pages/{page.slug.replace('-', '_')}.dart",
                     "\n".join(lines), self.name)

    def _widget(self, w) -> str:
        p = w.props
        if w.kind == "text":
            style = {"title": "headlineLarge", "heading": "headlineSmall", "subtitle": "titleMedium"}.get(str(p.get("variant") or ""), "bodyMedium")
            return f"Text({dart_str(str(p.get('text') or w.name))}, style: const TextStyle(fontWeight: FontWeight.w600))" if style == "bodyMedium" else f"Text({dart_str(str(p.get('text') or w.name))}, style: Theme.of(context).textTheme.{style})"
        if w.kind == "input":
            return f"TextField(decoration: const InputDecoration(labelText: {dart_str(str(p.get('label') or w.name))}))"
        if w.kind == "button":
            return f"FilledButton(onPressed: () {{}}, child: const Text({dart_str(str(p.get('label') or w.name))}))"
        if w.kind == "card":
            return f"Card(child: Padding(padding: const EdgeInsets.all(16), child: Text({dart_str(str(p.get('title') or w.name))})))"
        if w.kind == "navbar":
            return "Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [])"
        return f"Text({dart_str(w.name)})"


def module_name(name: str) -> str:
    import re
    s = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return s or "app"
