"""IntentLang compiler CLI.

Usage:
    python -m intentlang compile app.intentlang --out build [options]
    python -m intentlang check app.intentlang
    python -m intentlang explain app.intentlang
    python -m intentlang init my-app
    python -m intentlang watch app.intentlang --out build

Options:
    --frontend react|next|flutter
    --backend  fastapi|express|spring
    --database sqlite|postgres|mysql
    --incremental        use the disk cache
    --emit-ir            also write ir.json
    --no-docs --no-tests --no-docker --no-ci --no-deploy
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

from .compiler import CompileOptions, Compiler
from .incremental import IncrementalEngine

TEMPLATE = """// {name} — generated by IntentOS
// Describe the app in English in the IDE; the AI planner writes this file.
// This file is plain IntentLang: the compiler is 100% deterministic.

Create Application {name}
  With
    Title "{name}"
    Theme indigo
    Database sqlite

Create Page Home
  With
    Route /
    Title "Home"
  Add Text Welcome
    With
      Text "Welcome to {name}"
      Variant heading

Create Model Item
  With
    Table items
  Field Id
    Type id
  Field Name
    Type string
    Required true

Create Api ListItems
  With
    Method GET
    Route /api/items
    Auth public
  Query
    Select
    From items
  Response
    Status 200
    Body List Item

Deploy Docker
"""


def _options(args: argparse.Namespace) -> CompileOptions:
    return CompileOptions(
        frontend=args.frontend,
        backend=args.backend,
        database=args.database,
        include_docs=not args.no_docs,
        include_tests=not args.no_tests,
        include_docker=not args.no_docker,
        include_ci=not args.no_ci,
        include_deploy=not args.no_deploy,
    )


def cmd_compile(args: argparse.Namespace) -> int:
    sources: dict[str, str] = {}
    for path in args.files:
        p = Path(path)
        sources[p.name] = p.read_text(encoding="utf-8")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.incremental:
        engine = IncrementalEngine(Compiler(), out_dir / ".cache")
        result = engine.compile(sources, _options(args))
    else:
        root = sorted(sources)[0]
        result = Compiler().compile_source(sources[root], root, _options(args))

    for step in result.steps:
        status = "ok" if step.ok else "!!"
        print(f"[{status}] {step.name:<10} {step.elapsed_ms:>8.2f} ms  {step.detail}")

    for d in result.diagnostics.items:
        print(d.format(), file=sys.stderr)

    if result.ok() and result.artifacts.items:
        written = result.artifacts.write_to(out_dir)
        if args.emit_ir and result.module:
            (out_dir / "ir.json").write_text(
                result.module.to_json(), encoding="utf-8")
        print(f"\ncompiled {len(written)} artifacts -> {out_dir}")
        print(f"fingerprint: {result.fingerprint[:20]}...")
    elif not result.ok():
        print(f"\ncompile failed: {len(result.diagnostics.errors)} error(s)",
              file=sys.stderr)
        return 1
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    total = 0
    for path in args.files:
        p = Path(path)
        source = p.read_text(encoding="utf-8")
        result = Compiler().compile_source(source, p.name, _options(args),
                                           collect_artifacts=False)
        errs = len(result.diagnostics.errors)
        total += errs
        print(f"{p.name}: {errs} error(s)")
        for d in result.diagnostics.errors:
            print("  " + d.format())
    return 1 if total else 0


def cmd_explain(args: argparse.Namespace) -> int:
    for path in args.files:
        p = Path(path)
        source = p.read_text(encoding="utf-8")
        print(Compiler().explain(source, p.name))
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    name = args.name
    out = Path(args.out_dir) if args.out_dir else Path.cwd() / name
    out.mkdir(parents=True, exist_ok=True)
    target = out / "app.intentlang"
    if target.exists():
        print(f"{target} already exists; not overwriting", file=sys.stderr)
        return 1
    target.write_text(TEMPLATE.format(name=name), encoding="utf-8")
    print(f"created {target}")
    print("next: python -m intentlang compile " + str(target) + " --out build")
    return 0


def cmd_watch(args: argparse.Namespace) -> int:
    import threading
    cache: dict[str, float] = {}

    def run() -> None:
        sources: dict[str, str] = {}
        for path in args.files:
            p = Path(path)
            mtime = p.stat().st_mtime
            if cache.get(str(p)) == mtime:
                continue
            cache[str(p)] = mtime
            sources[p.name] = p.read_text(encoding="utf-8")
        if not sources:
            return
        cmd_compile(args)

    print(f"watching {args.files} (Ctrl-C to stop)")
    try:
        while True:
            run()
            time.sleep(1)
    except KeyboardInterrupt:
        print("\nstopped")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="intentlang",
                                     description="IntentLang compiler")
    sub = parser.add_subparsers(dest="command", required=True)

    c = sub.add_parser("compile", help="compile IntentLang to artifacts")
    c.add_argument("files", nargs="+")
    c.add_argument("--out", default="build")
    c.add_argument("--frontend", default="react")
    c.add_argument("--backend", default="fastapi")
    c.add_argument("--database", default="sqlite")
    c.add_argument("--incremental", action="store_true")
    c.add_argument("--emit-ir", action="store_true")
    c.add_argument("--no-docs", action="store_true")
    c.add_argument("--no-tests", action="store_true")
    c.add_argument("--no-docker", action="store_true")
    c.add_argument("--no-ci", action="store_true")
    c.add_argument("--no-deploy", action="store_true")
    c.set_defaults(func=cmd_compile)

    ch = sub.add_parser("check", help="check files without generating")
    ch.add_argument("files", nargs="+")
    ch.set_defaults(func=cmd_check)

    ex = sub.add_parser("explain", help="walk through the compilation")
    ex.add_argument("files", nargs="+")
    ex.set_defaults(func=cmd_explain)

    ini = sub.add_parser("init", help="scaffold a new IntentLang project")
    ini.add_argument("name")
    ini.add_argument("--out-dir", default=None)
    ini.set_defaults(func=cmd_init)

    wa = sub.add_parser("watch", help="recompile on file changes")
    wa.add_argument("files", nargs="+")
    wa.add_argument("--out", default="build")
    wa.set_defaults(func=cmd_watch)

    args = parser.parse_args(argv)
    if args.command == "watch":
        return cmd_watch(args)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
